spring:
  # thymeleaf??
  thymeleaf:
    cache: false
  # ?????
  datasource:
    # ???5.7???mysql??name???cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # hikari?springboot??????????????????????https://blog.csdn.net/cbmljs/article/details/87858536
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ???????????ms?????10??
      idle-timeout: 1800000
      # ????????10
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????0?????????1800000?30??
      max-lifetime: 1800000
      #??????30000?30?
      connection-timeout: 30000
      # ??????????????????????????????????????
      connection-test-query: SELECT 1

#mybatis-plus??
mybatis-plus:
  # ??mapper.xml????????mapper?????resource????????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??mybatis??????????????????https://blog.csdn.net/daijiguo/article/details/82827430
  type-aliases-package: com.zhangyun.zseckill.pojo

# mybatis????mysql???????????????????????????Mapper.xml??????https://blog.csdn.net/zlxls/article/details/77978281
logging:
  level:
    com.zhangyun.zsekill.mapper: debug

